apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api
  labels:
    app: recipe-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-api
  template:
    metadata:
      labels:
        app: recipe-api
    spec:
      containers:
        - name: recpie-api-server
          imagePullPolicy: Always
          image: darylnauman/project-two-recipe-api:%TAG%
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-api-service
spec:
  selector:
    app: recipe-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000